export const SCREEN = Object.freeze({
  MENU: 'MENU',
  SHAPES: 'GAME_SHAPES',
  ANIMAL_PUZZLE: 'GAME_ANIMAL_PUZZLE',
  SPACE: 'GAME_SPACE',
  ARCHAEOLOGY: 'GAME_ARCHAEOLOGY',
  FRUIT_CATCH: 'GAME_FRUIT_CATCH',
  CLAW: 'GAME_CLAW',
  CROCODILE_BRUSH: 'GAME_CROCODILE_BRUSH',
  HIDDEN_OBJECTS: 'GAME_HIDDEN_OBJECTS',
});

export const LANGUAGE = Object.freeze({
  VI: 'vi',
  EN: 'en',
});
