export const PLANET_CATALOG = Object.freeze([
  Object.freeze({
    nameKey: 'mercury',
    color: 0xb9b2aa,
    radius: 0.3,
    orbitRadius: 2.7,
    orbitSpeed: 0.98,
    angle: 0.15,
    inclination: 7,
    ascendingNode: 18,
  }),
  Object.freeze({
    nameKey: 'venus',
    color: 0xe8b56f,
    radius: 0.42,
    orbitRadius: 3.8,
    orbitSpeed: 0.78,
    angle: 2.35,
    inclination: 3.4,
    ascendingNode: 62,
  }),
  Object.freeze({
    nameKey: 'earth',
    color: 0x4e9fff,
    radius: 0.48,
    orbitRadius: 5.0,
    orbitSpeed: 0.62,
    angle: 4.45,
    inclination: 0,
    ascendingNode: 0,
    atmosphere: true,
  }),
  Object.freeze({
    nameKey: 'mars',
    color: 0xf07962,
    radius: 0.37,
    orbitRadius: 6.3,
    orbitSpeed: 0.5,
    angle: 1.05,
    inclination: 1.85,
    ascendingNode: 35,
  }),
  Object.freeze({
    nameKey: 'jupiter',
    color: 0xd6a77d,
    radius: 0.88,
    orbitRadius: 8.3,
    orbitSpeed: 0.34,
    angle: 3.25,
    inclination: 1.3,
    ascendingNode: 78,
    bands: true,
  }),
  Object.freeze({
    nameKey: 'saturn',
    color: 0xf2c77c,
    radius: 0.75,
    orbitRadius: 10.6,
    orbitSpeed: 0.27,
    angle: 5.45,
    inclination: 2.5,
    ascendingNode: 24,
    ring: 'saturn',
  }),
  Object.freeze({
    nameKey: 'uranus',
    color: 0x8ee6df,
    radius: 0.58,
    orbitRadius: 12.8,
    orbitSpeed: 0.22,
    angle: 2.05,
    inclination: 0.8,
    ascendingNode: 105,
    ring: 'uranus',
  }),
  Object.freeze({
    nameKey: 'neptune',
    color: 0x5479f0,
    radius: 0.57,
    orbitRadius: 15.0,
    orbitSpeed: 0.18,
    angle: 4.15,
    inclination: 1.8,
    ascendingNode: 58,
  }),
]);

export const SPACE_CAMERA_CONFIG = Object.freeze({
  minDistance: 7,
  maxDistance: 75,
});

export const SPACE_VISITOR_CONFIG = Object.freeze({
  firstDelay: Object.freeze([5, 8]),
  nextDelay: Object.freeze([9, 17]),
  maxVisitors: 2,
  minSpeed: 2.2,
  maxSpeed: 3.2,
});
